#!/usr/bin/env bash
# AiTechBlog — GSC Indexing List Sync Hook
#
# Keeps GSC_INDEXING.md in sync with _posts/.
# sitemap.xml itself is generated by jekyll-sitemap on every deploy and needs
# no maintenance — this hook only maintains the manual GSC submission list.
#
# Triggers (see .claude/settings.json):
#   - Write/Edit to _posts/*.md   (new post file written directly)
#   - Bash commands touching _posts/ or git mv/commit/push  (publish-post skill)

set -uo pipefail

INPUT=$(cat)

TOOL_NAME=$(echo "$INPUT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('tool_name',''))" 2>/dev/null || echo "")

case "$TOOL_NAME" in
  Write|Edit)
    FILE_PATH=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); i=d.get('tool_input',{}); print(i.get('file_path', i.get('path','')))" 2>/dev/null || echo "")
    # Only react to post files
    [[ "$FILE_PATH" == *"/_posts/"*.md ]] || exit 0
    ;;
  Bash)
    CMD=$(echo "$INPUT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('tool_input',{}).get('command',''))" 2>/dev/null || echo "")
    # Only react to commands that could have changed _posts/
    if ! echo "$CMD" | grep -qE '_posts|git[[:space:]]+(mv|commit|push|rm)'; then
      exit 0
    fi
    ;;
  *)
    exit 0
    ;;
esac

# Locate repo root (hook may run from any cwd)
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
[[ -n "$REPO_ROOT" ]] || exit 0
[[ -d "$REPO_ROOT/_posts" ]] || exit 0
[[ -f "$REPO_ROOT/GSC_INDEXING.md" ]] || exit 0

python3 "$REPO_ROOT/.claude/hooks/sync_indexing_list.py" "$REPO_ROOT"
exit 0
